# Generated by Django 4.2.23 on 2025-08-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0005_alter_notification_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text',
            field=models.TextField(default='Notification'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='OneSokoApp.message'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_status_updated', 'Order Status Updated'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('cart_item_added', 'Item Added to Cart'), ('cart_updated', 'Cart Updated'), ('cart_cleared', 'Cart Cleared'), ('product_inquiry', 'Product Inquiry'), ('product_inquiry_response', 'Product Inquiry Response'), ('product_low_stock', 'Product Low Stock'), ('product_out_of_stock', 'Product Out of Stock'), ('message_received', 'New Message Received'), ('message_reply', 'Message Reply'), ('new_order_received', 'New Order Received'), ('order_completed', 'Order Completed'), ('welcome', 'Welcome'), ('account_updated', 'Account Updated'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed')], max_length=50),
        ),
    ]
