version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.fullstack
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql://root:rootpassword@db:3306/onesoko_db
      - REDIS_URL=redis://redis:6379/1
      - DEBUG=false
    depends_on:
      - db
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: onesoko_db
      MYSQL_USER: onesoko_user
      MYSQL_PASSWORD: onesoko_password
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx-fullstack.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - web

volumes:
  mysql_data:
  static_volume:
  media_volume:
