# Generated by Django 5.2.4 on 2025-07-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_shopowner',
            field=models.BooleanField(default=False),
        ),
    ]
