# Generated by Django 4.2.23 on 2025-08-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0001_initial'),
    ]

    operations = [
    ]
