# Generated by Django 4.2.23 on 2025-08-13 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0002_auto_20250813_0949'),
    ]

    operations = [
    ]
