# Generated by Django 5.2.5 on 2025-08-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0003_shopratingsummary_shopreview_shopreviewresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewhelpfulvote',
            name='is_helpful',
            field=models.BooleanField(default=True),
        ),
    ]
