# Generated by Django 5.2.5 on 2025-08-18 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0004_reviewhelpfulvote_is_helpful'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('shop_created', 'Shop Created'), ('new_order', 'New Order'), ('order_status_update', 'Order Status Update'), ('new_review', 'New Review'), ('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock'), ('milestone', 'Milestone Achievement'), ('system', 'System Notification')], default='system', max_length=50),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='OneSokoApp__user_id_6bc249_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'type'], name='OneSokoApp__user_id_31dcf1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['timestamp'], name='OneSokoApp__timesta_39984a_idx'),
        ),
    ]
