# Generated by Django 5.2.4 on 2025-08-06 09:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0004_cart_cartitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='review_type',
            field=models.CharField(choices=[('product', 'Product Review'), ('shop', 'Shop Review')], default='product', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='OneSokoApp.shop'),
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=10),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('order_created', 'Order Created'), ('order_status_updated', 'Order Status Updated'), ('order_delivered', 'Order Delivered'), ('order_cancelled', 'Order Cancelled'), ('cart_item_added', 'Item Added to Cart'), ('cart_updated', 'Cart Updated'), ('cart_cleared', 'Cart Cleared'), ('product_inquiry', 'Product Inquiry'), ('product_inquiry_response', 'Product Inquiry Response'), ('product_low_stock', 'Product Low Stock'), ('product_out_of_stock', 'Product Out of Stock'), ('new_order_received', 'New Order Received'), ('order_completed', 'Order Completed'), ('welcome', 'Welcome'), ('account_updated', 'Account Updated'), ('payment_successful', 'Payment Successful'), ('payment_failed', 'Payment Failed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='OneSokoApp.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'product'), ('user', 'shop')},
        ),
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_inquiries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='OneSokoApp.product')),
                ('shop_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='inquiry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='OneSokoApp.productinquiry'),
        ),
    ]
