# Generated by Django 5.2.5 on 2025-08-18 10:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0006_orderanalytics_shippingaddress_ordertracking'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaignAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('campaign_type', models.CharField(choices=[('email', 'Email Marketing'), ('social', 'Social Media'), ('sms', 'SMS Marketing'), ('discount', 'Discount Campaign'), ('seasonal', 'Seasonal Campaign'), ('product_launch', 'Product Launch')], max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('conversions', models.IntegerField(default=0)),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_per_acquisition', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('return_on_investment', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='OneSokoApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='ProductPerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sold', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('reorder_point', models.IntegerField(default=5)),
                ('turnover_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('views_count', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('cart_abandonment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weekly_trend', models.CharField(choices=[('up', 'Trending Up'), ('down', 'Trending Down'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('last_sale_date', models.DateTimeField(blank=True, null=True)),
                ('peak_sales_period', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='OneSokoApp.product')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_orders', models.IntegerField(default=0)),
                ('completed_orders', models.IntegerField(default=0)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('new_customers', models.IntegerField(default=0)),
                ('returning_customers', models.IntegerField(default=0)),
                ('customer_lifetime_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('products_sold', models.IntegerField(default=0)),
                ('inventory_turnover', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('page_views', models.IntegerField(default=0)),
                ('unique_visitors', models.IntegerField(default=0)),
                ('conversion_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_analytics', to='OneSokoApp.shop')),
                ('top_selling_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OneSokoApp.product')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('shop', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CustomerBehaviorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_order_date', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('last_login_date', models.DateTimeField(blank=True, null=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('pages_viewed', models.IntegerField(default=0)),
                ('customer_segment', models.CharField(choices=[('new', 'New Customer'), ('regular', 'Regular Customer'), ('vip', 'VIP Customer'), ('at_risk', 'At Risk'), ('churned', 'Churned')], default='new', max_length=50)),
                ('preferred_categories', models.JSONField(blank=True, default=list)),
                ('favorite_products', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_analytics', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_behavior_analytics', to='OneSokoApp.shop')),
            ],
            options={
                'unique_together': {('customer', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='SalesForecasting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField()),
                ('forecast_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], max_length=20)),
                ('predicted_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('predicted_orders', models.IntegerField()),
                ('predicted_units_sold', models.IntegerField(blank=True, null=True)),
                ('confidence_level', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('actual_orders', models.IntegerField(blank=True, null=True)),
                ('actual_units_sold', models.IntegerField(blank=True, null=True)),
                ('accuracy_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='OneSokoApp.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_forecasts', to='OneSokoApp.shop')),
            ],
            options={
                'ordering': ['-forecast_date'],
                'unique_together': {('shop', 'product', 'forecast_date', 'forecast_type')},
            },
        ),
    ]
