# Generated by Django 5.2.5 on 2025-08-18 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0007_marketingcampaignanalytics_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLoyalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points_earned', models.IntegerField(default=0)),
                ('total_points_redeemed', models.IntegerField(default=0)),
                ('current_points_balance', models.IntegerField(default=0)),
                ('current_tier', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('annual_spending', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tier_progress', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('last_activity_date', models.DateTimeField(auto_now=True)),
                ('total_orders', models.IntegerField(default=0)),
                ('first_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('birthday_date', models.DateField(blank=True, null=True)),
                ('birthday_reward_claimed_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_accounts', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_customers', to='OneSokoApp.shop')),
            ],
            options={
                'verbose_name_plural': 'Customer Loyalty Accounts',
                'unique_together': {('customer', 'shop')},
            },
        ),
        migrations.CreateModel(
            name='CustomerReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('first_purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OneSokoApp.order')),
                ('referee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='OneSokoApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Loyalty Rewards', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('points_per_dollar', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('minimum_spend_for_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('points_expiry_days', models.IntegerField(default=365)),
                ('bronze_threshold', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('silver_threshold', models.DecimalField(decimal_places=2, default=500, max_digits=10)),
                ('gold_threshold', models.DecimalField(decimal_places=2, default=1500, max_digits=10)),
                ('platinum_threshold', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('bronze_multiplier', models.DecimalField(decimal_places=2, default=1.0, max_digits=3)),
                ('silver_multiplier', models.DecimalField(decimal_places=2, default=1.25, max_digits=3)),
                ('gold_multiplier', models.DecimalField(decimal_places=2, default=1.5, max_digits=3)),
                ('platinum_multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_program', to='OneSokoApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('discount_percentage', 'Percentage Discount'), ('discount_fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('free_product', 'Free Product'), ('bonus_points', 'Bonus Points')], max_length=20)),
                ('points_cost', models.IntegerField()),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('bonus_points_amount', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_redemptions_per_customer', models.IntegerField(default=1)),
                ('total_available', models.IntegerField(blank=True, null=True)),
                ('total_redeemed', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('minimum_tier_required', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum')], default='bronze', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('free_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OneSokoApp.product')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='OneSokoApp.shop')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('points_used', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('redeemed', 'Redeemed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('redemption_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='OneSokoApp.customerloyalty')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='OneSokoApp.order')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='OneSokoApp.loyaltyreward')),
            ],
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('earned_purchase', 'Points Earned from Purchase'), ('earned_signup', 'Welcome Bonus'), ('earned_referral', 'Referral Bonus'), ('earned_review', 'Review Bonus'), ('earned_birthday', 'Birthday Bonus'), ('earned_bonus', 'Special Bonus'), ('redeemed_discount', 'Redeemed for Discount'), ('redeemed_product', 'Redeemed for Product'), ('expired', 'Points Expired'), ('adjustment', 'Manual Adjustment')], max_length=20)),
                ('points_change', models.IntegerField()),
                ('points_balance_after', models.IntegerField()),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_loyalty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='OneSokoApp.customerloyalty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReferralProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('referrer_reward_points', models.IntegerField(default=100)),
                ('referee_reward_points', models.IntegerField(default=50)),
                ('minimum_purchase_amount', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_program', to='OneSokoApp.shop')),
            ],
        ),
    ]
