# Generated by Django 5.2.5 on 2025-08-20 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0010_alter_userprofile_options_userprofile_cover_photo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='users/covers/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user',)},
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='OneSokoApp_userprofile',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneSokoApp.product')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OneSokoApp.wishlist')),
            ],
            options={
                'ordering': ['-added_at'],
                'unique_together': {('wishlist', 'product')},
            },
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='products',
            field=models.ManyToManyField(related_name='wishlisted_by', through='OneSokoApp.WishlistItem', to='OneSokoApp.product'),
        ),
    ]
