# Generated by Django 5.2.5 on 2025-08-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OneSokoApp', '0011_userprofile_cover_photo_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='message',
            new_name='text',
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='inquiry_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
